name: Apply VIPC (ubuntu test)

on:
  workflow_dispatch:

jobs:
  apply-vipc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Run apply-vipc action (dry_run=true)
        uses: ./apply-vipc/action.yml
        with:
          minimum_supported_lv_version: '2021'
          vip_lv_version: '2021'
          supported_bitness: '64'
          relative_path: '.'
          vipm_toml: 'scripts/apply-vipc/vipm.toml'
          dry_run: true
